version: "3.3"
services:
  backend:
    container_name: backend
    build: gov-data-api/.
    volumes:
      - "./gov-data-api/:/serv"
    ports:
      - "8081:5000"
    depends_on:
      - "postgres"

  postgres:
    image: postgres:13.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: codam
      POSTGRES_DB: tomtom

  webapp:
    depends_on:
      - backend
    build: webapp/.
    volumes:
      - "./webapp:/serv"
    ports:
      - "8080:80"
